#!/usr/bin/env bash
echo "
+=====================+
|  Running Detekt...  |
+=====================+
"

./gradlew --no-daemon --stacktrace -PdisablePreDex detekt

detektStatus=$?

# return 1 exit code if running checks fails
[ $detektStatus -ne 0 ] && exit 1

echo "
+====================+
|  Running Tests...  |
+====================+
"

./gradlew --no-daemon --stacktrace -PdisablePreDex test

testStatus=$?

# return 1 exit code if running checks fails
[ $testStatus -ne 0 ] && exit 1
exit 0